name: Test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    environment: test-env
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install pnpm
        run: npm i -g pnpm
      - name: Install deps
        run: pnpm i
      - name: Install Cypress binary
        run: pnpm exec cypress install
      - name: Build
        run: pnpm run build
      - name: Run Cypress
        uses: cypress-io/github-action@v6
        with:
          install: false
          build: pnpm run build
          command: pnpm run test:ci

  test-push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install pnpm
        run: npm i -g pnpm
      - name: Install deps
        run: pnpm i
      - name: Install Cypress binary
        run: pnpm exec cypress install
      - name: Build
        run: pnpm run build
      - name: Run Cypress
        uses: cypress-io/github-action@v6
        with:
          install: false
          build: pnpm run build
          command: pnpm run test:ci